version: "3.8"
services:
  web:
    image: nginx:1.19.8
    container_name: nginx
    ports:
      - 8888:80
    volumes:
      - ./templates:/etc/nginx/templates
      - ./conf:/etc/nginx/conf.d
      - ./cache:/var/cache/nginx
      - ./static:/usr/share/nginx/html:ro
    command: [nginx-debug, '-g', 'daemon off;']
    environment:
      - APP_PROXY_URL

