version: "3.8"
services:
  web:
    image: nginx:1.19.8
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./cache:/var/cache/nginx
      - ./static:/usr/share/nginx/html:ro
    command: [nginx-debug, '-g', 'daemon off;']
